# Generated by Django 3.1.12 on 2021-08-21 17:59

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('options', djongo.models.fields.ArrayField(blank=True, model_container=api.models.Option)),
            ],
        ),
    ]
